name: fontainephotography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.00866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#040404'
    - '#676767'
    - '#8d8d8d'
    - '#4d4d4d'
  brandStrength: 0.6059783715754747
  lightness: 0.03168855817057192
  saturation: 0.007280409103259444
  rhythmicContrast: 0.00781843950971961
purpose: []
